# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


development:
  google_client_id: 571421253422-617kkctqi1m5oel5lb0j3njff01tlqpe.apps.googleusercontent.com
  google_client_secret: FMLI5i7zc2XSv-LVLIkytpBQ
  socrata_app_token: qTiLdwifqI81HjFYUfMJm1CPL
  socrata_secret_token: EKMNsmmj285VnDA6JVndc0s3IIoVN4_eyO_M
  account_sid: AC9845dbc5be3683da7a04141c96d92056
  auth_token: b0ff9759dc48805a92ccc81c0169b922
  SENDGRID_API_KEY: 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
  SENDGRID_USERNAME: adamjensen
  SENDGRID_PASSWORD: Stolen@2
  SKYLIGHT_AUTHENTICATION: m3gdpf9mKyAV7Vv-xuGyvQU10YpzuaJvqHpvwKnbobo

production:
  google_client_id: 571421253422-617kkctqi1m5oel5lb0j3njff01tlqpe.apps.googleusercontent.com
  google_client_secret: FMLI5i7zc2XSv-LVLIkytpBQ
  socrata_app_token: qTiLdwifqI81HjFYUfMJm1CPL
  socrata_secret_token: EKMNsmmj285VnDA6JVndc0s3IIoVN4_eyO_M
  account_sid: AC9845dbc5be3683da7a04141c96d92056
  auth_token: b0ff9759dc48805a92ccc81c0169b922
  SENDGRID_API_KEY: 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
  SENDGRID_USERNAME: adamjensen
  SENDGRID_PASSWORD: Stolen@2
  SKYLIGHT_AUTHENTICATION: m3gdpf9mKyAV7Vv-xuGyvQU10YpzuaJvqHpvwKnbobo

test:
  google_client_id: 571421253422-617kkctqi1m5oel5lb0j3njff01tlqpe.apps.googleusercontent.com
  google_client_secret: FMLI5i7zc2XSv-LVLIkytpBQ
  socrata_app_token: qTiLdwifqI81HjFYUfMJm1CPL
  socrata_secret_token: EKMNsmmj285VnDA6JVndc0s3IIoVN4_eyO_M
  account_sid: AC9845dbc5be3683da7a04141c96d92056
  auth_token: b0ff9759dc48805a92ccc81c0169b922
  test_token: ya29.bgJnotjzfngkgaf6EvtGI_IWOFr1tUkv2ZWos6zIjAZ_ARac9REM0K_nUjtJAU6KlXxWRw
  SENDGRID_API_KEY: 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
  SENDGRID_USERNAME: adamjensen
  SENDGRID_PASSWORD: Stolen@2
  SKYLIGHT_AUTHENTICATION: m3gdpf9mKyAV7Vv-xuGyvQU10YpzuaJvqHpvwKnbobo
